### First Stage ###
FROM golang:1.14-alpine AS builder
COPY . .
RUN go build -o server .

### Second Stage ###
FROM alpine:3.12
COPY --from=builder /go/server ./server
COPY index.html index.html
CMD ["./server"]